name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      BACKEND_APP_SERVICE_NAME: "app-backend-tf-prog2052"
      FRONTEND_APP_SERVICE_NAME: "app-frontend-tf-prog2052"
      RESOURCE_GROUP_NAME: "rg-tf-prog2052"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Backend App Settings tfvars File
        run: |
          cat > ./root/backend_app_settings.tfvars <<EOF
          backend_app_service_settings = {
            JWT_SECRET_KEY = "${{ secrets.JWT_SECRET_KEY }}"
            EMAIL_USER     = "${{ secrets.EMAIL_USER }}"
            SMTP_HOST      = "${{ secrets.SMTP_HOST }}"
            SMTP_PORT      = "${{ secrets.SMTP_PORT }}"
            EMAIL_PASS     = "${{ secrets.EMAIL_PASS }}"
          }
          EOF

      - name: Terraform Init (Backend)
        working-directory: ./root
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform init

      - name: Terraform Apply (Backend)
        working-directory: ./root
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform apply -auto-approve -var-file="backend_app_settings.tfvars"

      - name: Get Backend Hostname
        id: get_backend_hostname
        working-directory: ./root
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          echo "backend_hostname=$(terraform output -raw backend_app_service_default_hostname)" >> $GITHUB_ENV

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dailyverse-backend:latest

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        env:
          backend_hostname: ${{ env.backend_hostname }}
        with:
          context: ./frontend
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dailyverse-frontend:latest
          build-args: |
            REACT_APP_BACKEND_URL=https://${{ env.backend_hostname }}

      - name: Create Frontend App Settings tfvars File
        run: |
          cat > ./root/frontend_app_settings.tfvars <<EOF
          frontend_app_service_settings = {
            REACT_APP_BACKEND_URL = "https://${{ env.backend_hostname }}"
          }
          EOF

      - name: Terraform Apply (Frontend)
        working-directory: ./root
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform apply -auto-approve -var-file="frontend_app_settings.tfvars"

      - name: Restart Backend App Service
        run: |
          az webapp restart --name ${{ env.BACKEND_APP_SERVICE_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }}

      - name: Restart Frontend App Service
        run: |
          az webapp restart --name ${{ env.FRONTEND_APP_SERVICE_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }}
